name: Build and Release
on:
  workflow_dispatch:

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build for Mac
        if: matrix.os == 'macos-latest'
        run: python build_mac.py
        
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: python build_windows.py
        
      - name: Zip Mac artifacts
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r KnightSurvival-Mac.zip KnightSurvival
        shell: bash
        
      - name: Zip Windows artifacts
        if: matrix.os == 'windows-latest'
        run: |
          cd dist
          Compress-Archive -Path KnightSurvival.exe -DestinationPath KnightSurvival-Windows.zip
        shell: pwsh
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          files: dist/KnightSurvival-*.zip